services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tupi_fintech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tupi_fintech"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HTTP_ADDRESS: ":8080"
      APP_ENV: docker-compose
      LOG_LEVEL: INFO
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/tupi_fintech?sslmode=disable
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: tupi_fintech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
